//
//  FetchCartRequestModel.swift
//  DoorDash
//
//  Created by Marvin Zhan on 2018-10-10.
//  Copyright © 2018 Monster. All rights reserved.
//

struct FetchCartRequestModel {
    let cartID: String

    init(cartID: String) {
        self.cartID = cartID
    }

    func convertToQueryParams() -> [String: [String]] {
        var result: [String: [String]] = [:]
        result["expand"] = [
            "creator",
            "delivery_address",
            "delivery_address.address",
            "delivery_availability",
            "promotions",
            "store_order_carts",
            "store_order_carts.delivery",
            "store_order_carts.menu",
            "store_order_carts.orders",
            "store_order_carts.orders.consumer",
            "store_order_carts.orders.order_items",
            "store_order_carts.orders.order_items.item",
            "store_order_carts.orders.order_items.item.category",
            "store_order_carts.orders.order_items.options",
            "store_order_carts.orders.order_items.options.item_extra_option",
            "store_order_carts.orders.order_items.options.item_extra_option.item_extra",
            "store_order_carts.store"
        ]
        result["extra"] = [
            "cancelled_at",
            "creator",
            "creator.last_alcohol_delivery_time",
            "credited_amount_monetary_fields",
            "credited_amount_monetary_fields.currency",
            "credited_amount_monetary_fields.decimal_places",
            "currency",
            "delivery_address.address",
            "delivery_address.address.city",
            "delivery_address.address.country_code",
            "delivery_address.address.id",
            "delivery_address.address.lat",
            "delivery_address.address.lng",
            "delivery_address.address.printable_address",
            "delivery_address.address.shortname",
            "delivery_address.address.state",
            "delivery_address.address.subpremise",
            "delivery_address.address.zip_code",
            "delivery_address.dasher_instructions",
            "delivery_availability.is_outside_delivery_region",
            "delivery_fee_details",
            "delivery_fee_monetary_fields",
            "delivery_fee_monetary_fields.currency",
            "delivery_fee_monetary_fields.decimal_places",
            "discount_amount_monetary_fields",
            "discount_amount_monetary_fields.currency",
            "discount_amount_monetary_fields.decimal_places",
            "discount_details",
            "extra_sos_delivery_fee",
            "id",
            "is_group",
            "max_individual_cost",
            "min_age_requirement",
            "min_order_fee_monetary_fields",
            "min_order_fee_monetary_fields.currency",
            "min_order_fee_monetary_fields.decimal_places",
            "min_order_subtotal_monetary_fields",
            "min_order_subtotal_monetary_fields.currency",
            "min_order_subtotal_monetary_fields.decimal_places",
            "promotions",
            "refunded_amount_monetary_fields",
            "refunded_amount_monetary_fields.currency",
            "refunded_amount_monetary_fields.decimal_places",
            "service_fee_monetary_fields",
            "service_fee_monetary_fields.currency",
            "service_fee_monetary_fields.decimal_places",
            "service_rate_details",
            "shortened_url",
            "should_advertise_alcohol",
            "store_order_carts",
            "store_order_carts.all_fees_message",
            "store_order_carts.delivery",
            "store_order_carts.delivery.actual_delivery_time",
            "store_order_carts.delivery.actual_pickup_time",
            "store_order_carts.delivery.dasher",
            "store_order_carts.delivery.dasher_approaching_customer_time",
            "store_order_carts.delivery.dasher_assigned_time",
            "store_order_carts.delivery.dasher_at_store_time",
            "store_order_carts.delivery.dasher_route_available",
            "store_order_carts.delivery.quoted_delivery_time",
            "store_order_carts.delivery.store_confirmed_time",
            "store_order_carts.id",
            "store_order_carts.is_consumer_pickup",
            "store_order_carts.menu",
            "store_order_carts.orders",
            "store_order_carts.orders.id",
            "store_order_carts.orders.order_items",
            "store_order_carts.orders.order_items.id",
            "store_order_carts.orders.order_items.item",
            "store_order_carts.orders.order_items.item.category",
            "store_order_carts.orders.order_items.item.id",
            "store_order_carts.orders.order_items.item.name",
            "store_order_carts.orders.order_items.item.price_monetary_fields",
            "store_order_carts.orders.order_items.item.price_monetary_fields.currency",
            "store_order_carts.orders.order_items.item.price_monetary_fields.decimal_places",
            "store_order_carts.orders.order_items.options",
            "store_order_carts.orders.order_items.options.item_extra_option.description",
            "store_order_carts.orders.order_items.options.item_extra_option.id",
            "store_order_carts.orders.order_items.options.item_extra_option.item_extra",
            "store_order_carts.orders.order_items.options.item_extra_option.item_extra.name",
            "store_order_carts.orders.order_items.options.item_extra_option.name",
            "store_order_carts.orders.order_items.options.item_extra_option.price_monetary_fields",
            "store_order_carts.orders.order_items.options.item_extra_option.price_monetary_fields.currency",
            "store_order_carts.orders.order_items.options.item_extra_option.price_monetary_fields.decimal_places",
            "store_order_carts.orders.order_items.quantity",
            "store_order_carts.orders.order_items.special_instructions",
            "store_order_carts.orders.order_items.substitution_preference",
            "store_order_carts.orders.order_items.unit_price_monetary_fields",
            "store_order_carts.orders.order_items.unit_price_monetary_fields.currency",
            "store_order_carts.orders.order_items.unit_price_monetary_fields.decimal_places",
            "store_order_carts.service_fee_monetary_fields",
            "store_order_carts.service_fee_monetary_fields.currency",
            "store_order_carts.service_fee_monetary_fields.decimal_places",
            "store_order_carts.service_rate",
            "store_order_carts.service_rate_message",
            "store_order_carts.store",
            "store_order_carts.store.cover_img_url",
            "store_order_carts.store.header_image_url",
            "store_order_carts.store.id",
            "store_order_carts.store.is_good_for_group_orders",
            "store_order_carts.store.merchant_promotions",
            "store_order_carts.store.name",
            "store_order_carts.store.service_rate",
            "store_order_carts.store.store_disclaimers",
            "store_order_carts.tip_amount_monetary_fields",
            "store_order_carts.tip_amount_monetary_fields.currency",
            "store_order_carts.tip_amount_monetary_fields.decimal_places",
            "submitted_at",
            "subtotal_monetary_fields",
            "subtotal_monetary_fields.currency",
            "subtotal_monetary_fields.decimal_places",
            "tax_amount_monetary_fields",
            "tax_amount_monetary_fields.currency",
            "tax_amount_monetary_fields.decimal_places",
            "tip_amount_monetary_fields",
            "tip_amount_monetary_fields.currency",
            "tip_amount_monetary_fields.decimal_places",
            "tip_percentage_argument",
            "tip_suggestions",
            "total_before_tip_monetary_fields",
            "total_before_tip_monetary_fields.currency",
            "total_before_tip_monetary_fields.decimal_places"
        ]
        result["pickup_enabled_client"] = ["1"]
        return result
    }
}
